In [25]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
import pandas as pd
bc_card=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/201906.csv',encoding='utf-8', index_col=0)
bc_card.head()

,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,TP_GRP_NO,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,80,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,40,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,83,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52
3,201906,11,서울특별시,1144,마포구,11440660,서교동,80,음식,80,...,내국인,11,서울특별시,1138,은평구,1,20대,1,44174450,1790
4,201906,11,서울특별시,1120,성동구,11200550,사근동,80,음식,80,...,내국인,11,서울특별시,1120,성동구,1,20대,1,60338146,3536

(1) 카드 소비가 가장 많은 업종

In [50]:
bc_card['MAIN_BUZ_DESC'].value_counts()

생활     46736
음식     25598
쇼핑      7035
유흥      6263
T&E     6079
문화      4735
기타      2363
내구재     1192
Name: MAIN_BUZ_DESC, dtype: int64

(2) 수원시 거주 20대가 카드를 이용한 수 / 그 외

In [28]:
index1=bc_card[(bc_card['CSTMR_CTY_RGN_NM'] != '수원시')&(bc_card['AGE_VAL'] != '20대')].index
suwon_bc_card=bc_card.drop(index1)
suwon_bc_card.reset_index(drop=True, inplace=True)
len(suwon_bc_card)

23713

In [29]:
index2=bc_card[(bc_card['CSTMR_CTY_RGN_NM'] == '수원시')&(bc_card['AGE_VAL'] == '20대')].index
nonsuwon_bc_card=bc_card.drop(index2)
nonsuwon_bc_card.reset_index(drop=True, inplace=True)
len(nonsuwon_bc_card)

99632

(3) 수원시 거주 20대 중 업종별 이용금액과 이용건수 / 그 외

In [30]:
suwon_shop = pd.pivot_table(suwon_bc_card, index=['TP_BUZ_NM'], aggfunc='sum')
suwon_shop = suwon_shop.drop(['ADMI_CTY_NO','CTY_RGN_NO','TP_GRP_NO','MAIN_BUZ_CODE','REG_YYMM','CSTMR_CTY_RGN_NO','CSTMR_MEGA_CTY_NO','FLC','MEGA_CTY_NO','TP_BUZ_NO','SEX_CTGO_CD'], axis=1)
suwon_shop = suwon_shop.sort_values(by=['AMT','CNT'], ascending=[False, False])
suwon_shop.head()

<ipython-input-30-d5197d98160b>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  suwon_shop = pd.pivot_table(suwon_bc_card, index=['TP_BUZ_NM'], aggfunc='sum')

                   AMT     CNT
TP_BUZ_NM
인터넷 P/G    16833401312  672673
택   시       3944339409  522497
일반한식        3670138689  189278
서양음식        2514551076  302555
인터넷종합Mall   2335541290   56725

In [31]:
nonsuwon_shop = pd.pivot_table(nonsuwon_bc_card, index=['TP_BUZ_NM'], aggfunc='sum')
nonsuwon_shop = nonsuwon_shop.drop(['ADMI_CTY_NO','CTY_RGN_NO','TP_GRP_NO','MAIN_BUZ_CODE','REG_YYMM','CSTMR_CTY_RGN_NO','CSTMR_MEGA_CTY_NO','FLC','MEGA_CTY_NO','TP_BUZ_NO','SEX_CTGO_CD'], axis=1)
nonsuwon_shop = nonsuwon_shop.sort_values(by=['AMT','CNT'], ascending=[False, False])
nonsuwon_shop.head()

<ipython-input-31-21e499d0b485>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  nonsuwon_shop = pd.pivot_table(nonsuwon_bc_card, index=['TP_BUZ_NM'], aggfunc='sum')

                   AMT      CNT
TP_BUZ_NM
인터넷 P/G    90147575347  2137026
일반한식       18668279822   734938
인터넷종합Mall  16326981646   346210
이동통신요금     14397403082   191997
손해 보험      11175068868    83492

(4) 영등포에서의 한식 이용금액대 서양음식 이용금액

In [32]:
print(bc_card['TP_BUZ_NM'].unique())
print(bc_card['TP_BUZ_NO'].unique())

['서양음식' '편 의 점' '기타음료식품' '일반한식' '택   시' '한의원' '연 쇄 점' '스포츠레져용품' '인터넷 P/G'
 '구내매점(국가기관등)' '제 과 점' '인터넷종합Mall' '종합병원' '농축수산품' '주점' '화 장 품' '유아원'
 '대형할인점' '정장' '일반 서적' '약국' '인터넷Mall' '슈퍼 마켓' '일식회집' '당구장' '가전 제품' '중국음식'
 '의원' '영화관' '주 차 장' '기타잡화' '홈쇼핑' '손해 보험' '미곡상' '정기간행물' '스넥' '기타레져업'
 '정 육 점' '세탁소' '미 용 원' '기타숙박업' '특급 호텔' '면 세 점' '생명 보험' '이동통신요금' '농,축협직영매장'
 '완 구 점' '위탁급식업' '아동의류' '초중고교육기관' '사우나' '볼 링 장' '치과의원' '노래방' '문구용 품'
 '세 차 장' '신   발' '기타건강식' '기타용역서비스' '자동차부품' '기능학원' 'PG상품권' '공공 요금' '기타 교육'
 '외국어학원' '사무서비스' '화물 운송' '기념품 점' '학원(회원제형태)' '복지 매점' '헬스 크럽' '가정용품수리'
 '종합용역' '악세 사리' '시   계' '학습지교육' '티켓' '출판인쇄물' '위성방송' '자동차정비' '고속 버스'
 '항 공 사' '철   도' '한약방' '동물병원' '단란주점' '안경' '상품권' '옷감 직물' '보습학원' '병원'
 '정보서비스' '일반 가구' '소프트웨어' '의료 용품' '정 수 기' '애완 동물' '가례서비스' '피부미용실' '농협하나로클럽'
 '관광여행' '주 유 소' '비료/농약/사료/종자' '조세서비스' '목재,석재,철물' '레져업소(회원제형태)' '예체능학원'
 '미용 재료' '유흥주점' '기타가구' '전문 서적' '여 객 선' '기타의류' '내의판매점' '칵테일바' '조명 기구'
 '스포츠의류' '전자상거래 상품권' '귀 금 속' '기타수리서비스' '기타유통업' '화   원' '골프 용품' '주류판매점'
 '통신판매1' '기계 공구' '기타의료기관및기기' '기타전기제품' '맞춤복 점' '사진관' '독서실' '건강진단' '페 인 트'
 '철제 가구' '가   방' '렌 트 카' '치과병원' '일반백화점' '사무통신기기수리' '제 화 점' '주방용식기' '컴 퓨 터'
 '이 용 원' '화   랑' '수 영 장' '통신 기기' '주방 용구' '침구수예점' '사무 기기' '국산 신차' '기타건축자재'
 '기타사무용' 'DVD/음반/테이프판매' '이륜차판매' '기타비영리유통' '골프연습장' 'CATV' '성인용품점' '기타대인서비스'
 '1급 호텔' '기타회원제형태업소' '부동산중개/임대' '건축요업품' '문화취미기타' '기타컴퓨터' '안마/스포츠마사지'
 '골프경기장' '수 족 관' '스 키 장' '인테 리어' '인삼 제품' '부동산분양' '유류 판매' '수입자동차' '보일러펌프'
 '캐쥬얼의류' '통신서비스' '양 품 점' '제약회사' '보관창고업' '기타주방용구' '서적출판(회원제형태)' '농축수산가공품'
 '민예공예품' '자동차시트/타이어' '홍삼 제품' '한방병원' '기타교통수단' '신변잡화수리' '카 메 라' '대학등록금'
 '컴퓨터학원' '악 기 점' '기타서적문구' '와이셔츠/타이' '2급 호텔' '사무서비스(회원제형태)' '건강식품(회원제형태)'
 '종합레져타운' '중고자동차' '기타직물' '화방표구점' '윤활유전문판매' '카인테리어' '기타자동차서비스' '카페트커텐천막'
 'L P G' '기타농업관련' '산후조리원' '냉열 기기' '법률회계서비스' '유치원' '단체복']
[8006 4010 8399 8001 1123 7021 4021 2002 4076 4121 8301 4077 7001 8310
 8013 7110 5123 4004 4201 5001 7041 4078 4020 8004 2121 3101 8005 7020
 2250 6140 4499 4061 6210 8320 5003 8021 2199 8302 9210 7102 1020 1001
 4040 6201 9153 4110 5050 8031 4203 5121 7120 2111 7022 2130 5030 6130
 4421 8499 9199 6102 5102 4085 9140 5199 5101 9130 9121 4430 9305 4031
 2114 9202 9101 4412 4410 5106 2251 5010 9154 6110 1120 1101 1121 7042
 7050 8201 7105 4080 4301 5105 7010 9131 3001 9134 7112 3210 2240 9110
 7103 4111 1110 3301 9602 9160 9006 9301 5104 7111 8101 3099 5002 1122
 4299 4205 8010 9003 4208 4083 4411 9299 4099 2230 2001 8303 4060 9901
 7099 3199 4210 3402 5191 7060 9004 3002 4401 1130 7015 4001 9204 4420
 3202 5201 7101 2202 2113 5210 3201 4303 5202 6001 9099 5299 2020 6004
 4199 2102 9151 4481 7199 1002 9395 9133 9002 2299 5280 7121 2101 2220
 2110 9010 8402 9020 3304 6003 9001 4207 9150 4204 7040 9120 3299 9304
 4050 2215 6101 8401 7014 1199 9203 3401 5120 5103 2010 5099 4206 1003
 9303 9306 2120 6002 4399 2210 6103 6120 6199 4302 3302 9699 7044 3102
 9132 5122 4209]

In [33]:
bc_card_yong=bc_card[bc_card['CTY_RGN_NM']=='영등포구']
print(bc_card_yong['AMT'].sum(axis=0))

6941773658

In [34]:
index3 = bc_card_yong[bc_card_yong['TP_BUZ_NO']!=8001].index
bc_card_yongk = bc_card_yong.drop(index3)
bc_card_yongk.reset_index(drop=True, inplace=True)
bc_card_yongk['AMT'].sum(axis=0)
index4 = bc_card_yong[bc_card_yong['TP_BUZ_NO']!=8006].index
bc_card_yongu = bc_card_yong.drop(index4)
bc_card_yongu.reset_index(drop=True, inplace=True)
bc_card_yongu['AMT'].sum(axis=0)
print(bc_card_yongk['AMT'].sum(axis=0)) #한식 이용금액
print(bc_card_yongu['AMT'].sum(axis=0)) #서양 음식 이용금액

1042339522
448131494

(5) 서울시민 대 경기도민 이용건수

In [52]:
index5 = bc_card[bc_card['CSTMR_MEGA_CTY_NM']!='서울특별시'].index
bc_card_seoul = bc_card.drop(index5)
bc_card_seoul.reset_index(drop=True, inplace=True)
index6 = bc_card[bc_card['CSTMR_MEGA_CTY_NM']!='경기도'].index
bc_card_gyeong = bc_card.drop(index6)
bc_card_gyeong.reset_index(drop=True, inplace=True)
print(bc_card_seoul['CNT'].sum(axis=0)) #서울 이용건수
print(bc_card_gyeong['CNT'].sum(axis=0)) #경기도 이용건수

5542462
1921415

(6) 경기도에 거주하는 성별에 따른 이용금액과 이용건수

In [36]:
gyeongsex = pd.pivot_table(bc_card_gyeong, index = ['SEX_CTGO_CD','MAIN_BUZ_DESC'], aggfunc = 'sum')
gyeongsex = gyeongsex.drop(['ADMI_CTY_NO','CTY_RGN_NO','TP_GRP_NO','MAIN_BUZ_CODE','REG_YYMM','CSTMR_CTY_RGN_NO','CSTMR_MEGA_CTY_NO','FLC', 'MEGA_CTY_NO','TP_BUZ_NO'], axis=1)
gyeongsex = gyeongsex.reset_index()
gyeongsex = gyeongsex.sort_values(by=['SEX_CTGO_CD', 'AMT', 'CNT'], ascending=[True, False, False])
gyeongsex

<ipython-input-36-7a7b5dc0b634>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  gyeongsex = pd.pivot_table(bc_card_gyeong, index = ['SEX_CTGO_CD','MAIN_BUZ_DESC'], aggfunc = 'sum')

    SEX_CTGO_CD MAIN_BUZ_DESC          AMT     CNT
4             1            생활  17874073676  590200
7             1            음식   2598170639  134231
1             1            기타   2145184633   36533
0             1           T&E   2019556385  133024
2             1           내구재   1792732653    3061
5             1            쇼핑    902543299   22633
3             1            문화    334543529   13962
6             1            유흥    241657041   12455
12            2            생활  21447623156  589433
9             2            기타   1976230799   29873
13            2            쇼핑   1938595390   37915
8             2           T&E   1935035224  164557
15            2            음식   1720711741  122259
11            2            문화    552172668   18942
10            2           내구재    341671545    2879
14            2            유흥    122485026    9458

(7) 나이에 따른 고객 수

In [37]:
bc_card_copy = bc_card.copy()

In [38]:
bc_card_copy['AGE_VAL'].unique()
mapping = {'20세 미만': 10, '20대': 20, '30대': 30, '40대': 40, '50대' : 50, '60대 이상' : 60}
bc_card_copy['AGE_VAL'] = bc_card_copy['AGE_VAL'].map(mapping)
bc_card_copy

,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,TP_GRP_NO,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,80,...,내국인,11,서울특별시,1162,관악구,2,30,2,26284804,1892
1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,40,...,내국인,11,서울특별시,1165,서초구,2,20,1,109290,18
2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,83,...,내국인,11,서울특별시,1162,관악구,1,20,1,268850,52
3,201906,11,서울특별시,1144,마포구,11440660,서교동,80,음식,80,...,내국인,11,서울특별시,1138,은평구,1,20,1,44174450,1790
4,201906,11,서울특별시,1120,성동구,11200550,사근동,80,음식,80,...,내국인,11,서울특별시,1120,성동구,1,20,1,60338146,3536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99996,201906,11,서울특별시,1165,서초구,11650520,서초2동,30,생활,40,...,내국인,43,충청북도,4311,청주시,1,50,4,50600,10
99997,201906,11,서울특별시,1117,용산구,11170520,용산2가동,30,생활,40,...,내국인,11,서울특별시,1162,관악구,1,40,2,38640,7
99998,201906,11,서울특별시,1156,영등포구,11560535,영등포동,30,생활,40,...,내국인,28,인천광역시,2817,미추홀구,2,30,2,340590,15
99999,201906,11,서울특별시,1141,서대문구,11410585,신촌동,40,쇼핑,42,...,내국인,44,충청남도,4413,천안시,1,20,2,117100,3
100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,51,...,내국인,41,경기도,4115,의정부시,1,40,3,5227500,7

In [39]:
ind1=bc_card_copy[bc_card_copy['AGE_VAL']>=40].index
age_bc_card=bc_card_copy.drop(ind1)
age_bc_card.reset_index(drop=True, inplace=True)
len(age_bc_card) #30대 이하

48368

In [40]:
ind2=bc_card_copy[bc_card_copy['AGE_VAL']<=30].index
age_bc_card2=bc_card_copy.drop(ind2)
age_bc_card2.reset_index(drop=True, inplace=True)
len(age_bc_card2) #40대 이상

51633

(8) 나이에 따른 카드의 이용장소와 이용금액

In [41]:
ten_agebuz = pd.pivot_table(age_bc_card, index = ['CTY_RGN_NM'], aggfunc = 'sum')
ten_agebuz = ten_agebuz.drop(['AGE_VAL','ADMI_CTY_NO','CTY_RGN_NO','TP_GRP_NO','MAIN_BUZ_CODE','REG_YYMM','CSTMR_CTY_RGN_NO','CSTMR_MEGA_CTY_NO','FLC', 'MEGA_CTY_NO','TP_BUZ_NO','SEX_CTGO_CD'], axis=1)
ten_agebuz = ten_agebuz.reset_index()
ten_agebuz = ten_agebuz.sort_values(by=['AMT', 'CNT'], ascending=[False, False])
ten_agebuz.head()

<ipython-input-41-d5f3b246d182>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  ten_agebuz = pd.pivot_table(age_bc_card, index = ['CTY_RGN_NM'], aggfunc = 'sum')

   CTY_RGN_NM          AMT      CNT
23         중구  24711141724  1170074
20        용산구  13349358974   798531
0         강남구  12636361198   544095
12        마포구  12579263355   548713
6         구로구   8855040995   309645

In [42]:
four_agebuz = pd.pivot_table(age_bc_card2, index = ['CTY_RGN_NM'], aggfunc = 'sum')
four_agebuz = four_agebuz.drop(['AGE_VAL','ADMI_CTY_NO','CTY_RGN_NO','TP_GRP_NO','MAIN_BUZ_CODE','REG_YYMM','CSTMR_CTY_RGN_NO','CSTMR_MEGA_CTY_NO','FLC', 'MEGA_CTY_NO','TP_BUZ_NO','SEX_CTGO_CD'], axis=1)
four_agebuz = four_agebuz.reset_index()
four_agebuz = four_agebuz.sort_values(by=['AMT', 'CNT'], ascending=[False, False])
four_agebuz.head()

<ipython-input-42-5a50c28990a0>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  four_agebuz = pd.pivot_table(age_bc_card2, index = ['CTY_RGN_NM'], aggfunc = 'sum')

   CTY_RGN_NM          AMT     CNT
23         중구  34094645156  934829
0         강남구  22899287304  542410
14        서초구  15571299362  225058
20        용산구  11648566820  279890
6         구로구  11094436620  299168

(9) 나이대별 최대 이용 업종

In [43]:
agebuz = pd.pivot_table(age_bc_card, index = ['AGE_VAL','TP_BUZ_NM'], aggfunc = 'sum')
agebuz = agebuz.drop(['ADMI_CTY_NO','CTY_RGN_NO','TP_GRP_NO','MAIN_BUZ_CODE','REG_YYMM','CSTMR_CTY_RGN_NO','CSTMR_MEGA_CTY_NO','FLC', 'MEGA_CTY_NO','TP_BUZ_NO','SEX_CTGO_CD'], axis=1)
agebuz = agebuz.reset_index()
agebuz = agebuz.sort_values(by=['AGE_VAL','AMT', 'CNT'], ascending=[True, False, False])
idx = agebuz.groupby('AGE_VAL')['AMT'].idxmax()
agebuz_max_spending = agebuz.loc[idx]
print(agebuz_max_spending)

     AGE_VAL TP_BUZ_NM          AMT     CNT
46        10   인터넷 P/G    199193411   18816
184       20   인터넷 P/G  13318131743  596239
373       30   인터넷 P/G  25255090129  667441

<ipython-input-43-e3a46fc580fe>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  agebuz = pd.pivot_table(age_bc_card, index = ['AGE_VAL','TP_BUZ_NM'], aggfunc = 'sum')

In [44]:
agebuz2 = pd.pivot_table(age_bc_card2, index = ['AGE_VAL','TP_BUZ_NM'], aggfunc = 'sum')
agebuz2 = agebuz2.drop(['ADMI_CTY_NO','CTY_RGN_NO','TP_GRP_NO','MAIN_BUZ_CODE','REG_YYMM','CSTMR_CTY_RGN_NO','CSTMR_MEGA_CTY_NO','FLC', 'MEGA_CTY_NO','TP_BUZ_NO','SEX_CTGO_CD'], axis=1)
agebuz2 = agebuz2.reset_index()
agebuz2 = agebuz2.sort_values(by=['AGE_VAL','AMT', 'CNT'], ascending=[True, False, False])
idx2 = agebuz2.groupby('AGE_VAL')['AMT'].idxmax()
agebuz_max_spending2 = agebuz2.loc[idx2]
print(agebuz_max_spending2)

     AGE_VAL TP_BUZ_NM          AMT     CNT
120       40   인터넷 P/G  25864045701  535132
308       50   인터넷 P/G  15346918678  237233
490       60   인터넷 P/G  10944438831  143301

<ipython-input-44-d71e73209db4>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  agebuz2 = pd.pivot_table(age_bc_card2, index = ['AGE_VAL','TP_BUZ_NM'], aggfunc = 'sum')

(10) 영등포에 거주하는 / 비거주하는 사람들의 음료식품 소비금액

In [45]:
bc_card_drink=bc_card[bc_card['TP_BUZ_NO']==8399]
bc_card_drink['AMT'].sum(axis=0)

790508985

In [46]:
bc_card_yong=bc_card[bc_card['CTY_RGN_NM']=='영등포구']
print(bc_card_yong['AMT'].sum(axis=0))

6941773658

In [47]:
bc_card_yong_drink=bc_card[(bc_card['TP_BUZ_NO']==8399)&(bc_card['CTY_RGN_NM']=='영등포구')]
bc_card_yong_drink['AMT'].sum(axis=0) #기타음료식품

109133335

In [53]:
bc_card_yong = bc_card_yong_drink
ind3 = bc_card_yong_drink[bc_card_yong_drink['CSTMR_CTY_RGN_NM']=='영등포구'].index
bc_card_yong1 = bc_card_yong_drink.drop(ind3)
bc_card_yong1.reset_index(drop=True, inplace=True)
ind4 = bc_card_yong_drink[bc_card_yong_drink['CSTMR_CTY_RGN_NM']!='영등포구'].index
bc_card_yong2 = bc_card_yong_drink.drop(ind4)
bc_card_yong2.reset_index(drop=True, inplace=True)
print(bc_card_yong1['AMT'].sum(axis=0)) #영등포 비거주
print(bc_card_yong2['AMT'].sum(axis=0)) #영등포 거주

96746835
12386500